apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_flask_api
  labels:
    app: my_flask_api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my_flask_api
  template:
    metadata:
      labels:
        app: my_flask_api
    spec:
      containers:
      - name: my_flask_api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
