apiVersion: v1
kind: Service
metadata:
  name: my_flask_api_service
  labels:
    app: my_flask_api
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: my_flask_api
  type: {{ .Values.service.type }}
