replicaCount: 5

image:
  repository: ofirzvishaboo/flask_name_api
  tag: latest

service:
  type: NodePort
  selector:
    component: app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000 
