replicaCount: 2
image:
  repository: giladouzan/flask_api_app
  tag: latest # Or specific tag as needed
service:
  type: LoadBalancer
appPort: 3000 # Optional if different from container port
database:
  host: "db" # Assuming service name from docker-compose.yml
  port: 3306
  user: "root"
  password: "pythoncourse"
  db: "MyDB_AdvancedProject"